name: lukehog
description: Simple analytics for pure dart projects
version: 0.1.0
repository: https://github.com/lukepighetti/lukehog
homepage: https://lukehog.com

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.4.4

dependencies:
  http: ^1.2.2
  nanoid2: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
